#!/bin/bash

# Restauration des fichiers de l'application (src/app)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

cd "$PROJECT_ROOT"

echo "  📄 Création de src/app/layout.tsx..."
cat > src/app/layout.tsx << 'EOF'
import type { Metadata } from "next";
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ErrorReporter />
        <Script
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
          strategy="afterInteractive"
          data-target-origin="*"
          data-message-type="ROUTE_CHANGE"
          data-include-search-params="true"
          data-only-in-iframe="true"
          data-debug="true"
          data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
        />
        {children}
        <VisualEditsMessenger />
      </body>
    </html>
  );
}
EOF

echo "  📄 Création de src/app/page.tsx..."
cat > src/app/page.tsx << 'EOF'
import SidebarNavigation from "@/components/sections/sidebar-navigation";
import MainHeader from "@/components/sections/main-header";
import NewsFeed from "@/components/sections/news-feed";
import AnalyticsSidebar from "@/components/sections/analytics-sidebar";
import MobileHeader from "@/components/sections/mobile-header";

export default function Home() {
  return (
    <div className="relative min-h-screen bg-background">
      <MobileHeader>
        <SidebarNavigation />
      </MobileHeader>

      <SidebarNavigation />

      <main className="md:ml-[256px] peer-data-[collapsible=icon]:md:ml-[64px] transition-[margin-left] duration-200 ease-linear">
        <div className="relative mx-auto max-w-5xl pt-14 md:pt-0">
          <MainHeader />
          
          <div className="px-4 pb-8 md:px-8">
            <NewsFeed />
          </div>
        </div>
      </main>

      <AnalyticsSidebar />
    </div>
  );
}
EOF

echo "  📄 Création de src/app/global-error.tsx..."
cat > src/app/global-error.tsx << 'EOF'
"use client";

import ErrorReporter from "@/components/ErrorReporter";

export default ErrorReporter;
EOF

echo "  📄 Création de src/app/globals.css..."
cat > src/app/globals.css << 'EOF'
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

@import "tailwindcss";
@import "tw-animate-css";
@custom-variant dark (&:is(.dark *));

@theme {
  --color-background: #ffffff;
  --color-foreground: #111827;

  --color-card: #ffffff;
  --color-card-foreground: #111827;

  --color-popover: #ffffff;
  --color-popover-foreground: #111827;

  --color-primary: #111827;
  --color-primary-foreground: #ffffff;

  --color-secondary: #f3f4f6;
  --color-secondary-foreground: #111827;

  --color-muted: #f9fafb;
  --color-muted-foreground: #6b7280;

  --color-accent: #f3f4f6;
  --color-accent-foreground: #111827;

  --color-destructive: #ef4444;
  --color-destructive-foreground: #ffffff;

  --color-border: #e5e7eb;
  --color-input: #e5e7eb;
  --color-ring: #111827;

  --color-chart-1: #3b82f6;
  --color-chart-2: #ec4899;
  --color-chart-3: #1e3a5f;
  --color-chart-4: #f1c40f;
  --color-chart-5: #e74c3c;

  --color-sidebar: #f9fafb;
  --color-sidebar-foreground: #111827;
  --color-sidebar-primary: #111827;
  --color-sidebar-primary-foreground: #ffffff;
  --color-sidebar-accent: #f3f4f6;
  --color-sidebar-accent-foreground: #111827;
  --color-sidebar-border: #e5e7eb;
  --color-sidebar-ring: #111827;

  --radius-lg: 0.5rem;
  --radius-md: calc(0.5rem - 2px);
  --radius-sm: calc(0.5rem - 4px);

  --animate-accordion-down: accordion-down 0.2s ease-out;
  --animate-accordion-up: accordion-up 0.2s ease-out;

  @keyframes accordion-down {
    from {
      height: 0;
    }
    to {
      height: var(--radix-accordion-content-height);
    }
  }
  @keyframes accordion-up {
    from {
      height: var(--radix-accordion-content-height);
    }
    to {
      height: 0;
    }
  }

  --color-surface: #f9fafb;
  --color-text-primary: #111827;
  --color-text-secondary: #6b7280;
  --color-text-muted: #9ca3af;
  --color-accent-cyan: #06b6d4;
  --color-accent-violet: #8b5cf6;
  --color-accent-pink: #ec4899;
  --color-button-primary: #111827;
  --color-button-secondary: #ffffff;
  --color-hover-accent: #f3f4f6;
  --color-active-accent: #f3f4f6;

  --font-primary: "Inter", sans-serif;
}

/*
  The default border color has changed to currentColor in Tailwind CSS v4,
  so we've added these compatibility styles to make sure everything still
  looks the same as it did with Tailwind CSS v3.

  If we ever want to remove these styles, we need to add an explicit border
  color utility to any element that depends on these defaults.
*/
@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-border);
  }
}

@layer utilities {
  body {
    font-family: var(--font-primary);
  }
}

@layer base {
  :root {
    --background: var(--color-background);
    --foreground: var(--color-foreground);
    --card: var(--color-card);
    --card-foreground: var(--color-card-foreground);
    --popover: var(--color-popover);
    --popover-foreground: var(--color-popover-foreground);
    --primary: var(--color-primary);
    --primary-foreground: var(--color-primary-foreground);
    --secondary: var(--color-secondary);
    --secondary-foreground: var(--color-secondary-foreground);
    --muted: var(--color-muted);
    --muted-foreground: var(--color-muted-foreground);
    --accent: var(--color-accent);
    --accent-foreground: var(--color-accent-foreground);
    --destructive: var(--color-destructive);
    --destructive-foreground: var(--color-destructive-foreground);
    --border: var(--color-border);
    --input: var(--color-input);
    --ring: var(--color-ring);
    --chart-1: var(--color-chart-1);
    --chart-2: var(--color-chart-2);
    --chart-3: var(--color-chart-3);
    --chart-4: var(--color-chart-4);
    --chart-5: var(--color-chart-5);
    --radius: var(--radius-lg);
    --sidebar-background: var(--color-sidebar);
    --sidebar-foreground: var(--color-sidebar-foreground);
    --sidebar-primary: var(--color-sidebar-primary);
    --sidebar-primary-foreground: var(--color-sidebar-primary-foreground);
    --sidebar-accent: var(--color-sidebar-accent);
    --sidebar-accent-foreground: var(--color-sidebar-accent-foreground);
    --sidebar-border: var(--color-sidebar-border);
    --sidebar-ring: var(--color-sidebar-ring);
  }

  html {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  body {
    font-family: var(--font-primary);
    font-size: 14px;
    line-height: 20px;
    color: var(--color-text-primary);
  }

  h1 {
    font-size: 28px;
    font-weight: 700;
    line-height: 36px;
  }

  h2 {
    font-size: 16px;
    font-weight: 600;
    line-height: 22px;
  }

  p {
    font-size: 14px;
    line-height: 20px;
  }

  small {
    font-size: 12px;
    line-height: 16px;
  }

  .text-subtitle {
    font-size: 14px;
    font-weight: 400;
    line-height: 20px;
    color: var(--color-text-secondary);
  }

  .text-sidebar-label {
    font-size: 12px;
    font-weight: 500;
    line-height: 16px;
    color: var(--color-text-muted);
  }

  .text-sidebar-menu {
    font-size: 14px;
    font-weight: 400;
    line-height: 20px;
  }

  .text-ranking-number {
    font-size: 14px;
    font-weight: 600;
    line-height: 20px;
  }

  .text-stats {
    font-size: 32px;
    font-weight: 700;
    line-height: 40px;
  }
}

/* Hide Next.js error overlay portal */
nextjs-portal {
  display: none !important;
}
EOF

echo "  ✅ Fichiers de l'application créés"
